config/routes.rb
Rails.application.routes.draw do
  devise_for :users

   root 'welcome#index'

   resources :locations do
    resources :cohorts
  end

  resources :assignments do
    resources :submissions do      
      member do
        get :grade
      end
      resources :links
    end
  end

  resources :courses

  resources :comments

end

app/controllers/locations_controller.rb
class locationsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_location, only: [:show, :edit, :update, :destroy]
  

  def index
    @locations = location.all
  end

  def show
    
  @location = Location.find params[:id]
  @clients = @location.clients
  end

  def new
    @location = Location.new

  end

  def create
    @location = Location.create location_params
    if @location.save == true
    redirect_to locations_path
    else
    render :new
    end
  end
   
  def edit
    @location = Location.find params[:id]
  end

  def update
    @location = Location.find params[:id]
    @location.update_attributes location_params
    redirect_to locations_path
  end

  def destroy
    @location = Location.find params[:id]
    @location.delete
    redirect_to locations_path
  end
private
  def find_location
    @location = Location.find params[:id]
  end
  
  def location_params
    params.require(:location).permit(:city, :state)
  end
  
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/views/locations/_form.html.haml
= form_for @location do |f|
  = if f.object.errors.messages.length > 0
    <!-- Render the errors to the user -->
    = f.object.errors.messages.inspect  
    %br
      -f.object.errors.messages.each do |key, value| 
        -value.each do |message| 
          = key = message 
          %br
  = f.text_field :city, class: 'form-control focusedInput', placeholder: 'Add City Here...'
  = f.text_field :state, class: 'form-control focusedInput', placeholder: 'Add State Here...'
  =f.submit "Add Location", class: 'btn btn-success btn-block'

app/views/locations/edit.html.haml
 %h1
  Edit Location
= render 'form'

app/views/locations/index.html.haml
- @locations.each do |location|
  .col-md-12
    - if current_user.try(:admin?)
      = link_to "Edit", edit_location_path(location), :class=> "btn btn-info btn-xs"
      = link_to "Delete", location_path(location), method: :delete, :class=>"btn btn-danger btn-xs"
    %strong
      = link_to location.name, location_path(location)
    = location.address
.col-md-12
  - if current_user.try(:admin?)
    = link_to "New Location", new_location_path
  %br
  = link_to "Back", root_path

app/views/locations/new.html.haml
%h1 New Locations

= render 'form'

app/views/locations/show.html.haml
%h1 The HomeworkTracker
%strong
  Name:
= @location.name
%br
%strong

%br
= link_to "Create User", new_location_user_path(@location)
%ul
  /= @location.users.inspect
  - @location.users.each do |user|
    %li
      = link_to "#{user.firstname} | #{user.lastname}", location_user_path(@location, user)
      |
      = link_to "Edit", edit_location_user_path(@location, user)
      |
      = link_to "Delete", location_user_path(@location, user), method: :delete
%br
%p Doctors

-@doctors.each do |f|
  %li  
    = f.name
    |
    = link_to "delete", delete_doctor_location_path(@location, @user, doctor_id: f.id), method: :delete
    %br
%br
= form_for @doctor, url: create_doctor_location_path(@location, @user) do |f|
  = f.label "Add New Doctor"
  %br
  = f.text_area :name
  %br
  = f.submit

%br
%li= link_to "Back", locations_path(@location)